# Copyright Materialize, Inc. and contributors. All rights reserved.
#
# Use of this software is governed by the Business Source License
# included in the LICENSE file.
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the Apache License, Version 2.0.

# Datadriven tests for the equality-saturation pass (`apply pipeline=eqsat`).
# The expected outputs are generated by `REWRITE=1 cargo test -p mz-transform
# --test test_transforms`.

# Source definitions
# ------------------

define
DefSource name=t0
  - c0: bigint
  - c1: bigint
----
Source defined as t0

# Case (a): nested filters fuse to one filter.
#
# The merge_filters rule rewrites `filter(p, filter(q, r))` into a single
# `filter(p && q, r)`, reducing the operator count.
apply pipeline=eqsat
Filter (#0)
  Filter (#1)
    Get t0
----
Filter #0 AND #1
  Get t0

# Case (b): filter distributes over a union, then inner filters fuse.
#
# `distribute_filter_union_nary` pushes the outer filter into each branch;
# `merge_filters` then fuses it with the per-branch filters.
apply pipeline=eqsat
Filter (#0)
  Union
    Filter (#1)
      Get t0
    Filter (#1)
      Get t0
----
Union
  Filter #0 AND #1
    Get t0
  Filter #0 AND #1
    Get t0

# Case (c): unsupported node (Reduce) under a Filter is preserved verbatim.
#
# The egraph pass bails out at unsupported variants, so the Reduce is returned
# intact and only the supported outer Filter envelope may be rewritten.
apply pipeline=eqsat
Filter (#0)
  Reduce group_by=[#0] aggregates=[]
    Get t0
----
Filter #0
  Distinct project=[#0]
    Get t0

# Case (d): filter with a literal-false predicate rewrites to an empty constant.
#
# `empty_false_filter` fires (`Filter[false] r => Empty(r)`), and extraction
# picks the cheaper Constant. Raise must produce an empty collection of arity 2,
# not panic.
apply pipeline=eqsat
Filter (false)
  Get t0
----
Constant <empty>

# Case (e): a constant Map scalar is folded at lower time.
#
# `reduced_escalar` runs `MirScalarExpr::reduce` on the payload, so `1 + 1`
# is stored (and raised) as the literal `2`.
apply pipeline=eqsat
Map (1 + 1)
  Get t0
----
Map (2)
  Get t0

# Case (g): contradictory equivalences collapse to empty.
#
# The filter has two predicates #0 = 1 and #0 = 2. The equivalences analysis
# places them in one class [#0 = 1, #0 = 2, true], which after minimize
# yields class [#0, 1, 2]: two distinct literals forced equal, unsatisfiable.
# The `collapse_unsatisfiable` rule rewrites any such relation to Empty.
apply pipeline=eqsat
Filter ((#0 = 1) AND (#0 = 2))
  Get t0
----
Constant <empty>

# Case (h): equality predicate canonicalized by join equivalences, but retained.
#
# The inner join forces #0 = #2. The canonicalization step rewrites #2 to #0
# (canonical representative) in the FILTER predicate, turning #0 = #2 into
# #0 = #0. The join's own equivalence [#0, #2] is NOT rewritten: applying the
# join's output reducer back to the join's own conditions is circular and unsound
# (it would turn an equijoin into a weaker join, producing extra rows). The
# filter #0 = #0 is pushed into the first join input by push_filter_into_join_first.
# The filter is NOT dropped: dropping Filter[#a=#b] when the input's equivalences
# prove #a=#b is unsound for null-preserving sources (the equivalences analysis
# has no nullability facts), so that step is deferred to the typed/physical phase.
define
DefSource name=t1
  - c0: bigint
  - c1: bigint
----
Source defined as t1

apply pipeline=eqsat
Filter (#0 = #2)
  Join on=(#0 = #2)
    Get t0
    Get t1
----
Join on=(#0 = #2)
  Filter (#0 = #0)
    Get t0
  Get t1

# Case (f): equivalence-canonical scalar rewriting.
#
# The Filter establishes #0 = #1. The Map computes #1 + 1 over that input.
# The equivalences analysis for the Map's e-class knows:
#   - #0 = #1 (from the filter below it),
#   - col2 = #0 + 1 (= #1 + 1, the Map's own new column).
# The Map scalar #1 + 1 is rewritten to #0 + 1 (using the Map's e-class reducer,
# which includes the filter's #0 = #1 fact from the input). This rewrite is correct
# because the fact comes from the Map's input chain, not from the Map's own scalars.
# The second equivalence (#0+1 -> col2=#2) is rejected by the validity guard:
# rewriting the Map scalar at pos=0 to column(input_arity+0)=column(2) would
# produce a forward self-reference to the column the Map is still constructing.
#
# The filter predicate #0 = #1 is NOT rewritten. The Filter's own equivalences
# include the fact `#0 = #1` derived from the predicate itself, which would map
# #1 → #0 and rewrite the predicate to #0 = #0 (trivially true, causing the filter
# to be dropped). Using only the input's (Get t0's) reducer avoids this circular
# rewrite. Get t0 has no non-trivial equivalences, so the predicate stays as #0 = #1.
apply pipeline=eqsat
Map (#1 + 1)
  Filter (#0 = #1)
    Get t0
----
Filter (#0 = #1)
  Map ((#0 + 1))
    Get t0
